/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contactbookfrog;
import java.awt.Color;
import static javax.swing.JOptionPane.showMessageDialog;
/**
 *
 * @author Jolou
 */
public class UserInterface extends javax.swing.JFrame {
    
    /**
     * Call pre-defined classes
     */
    ValidateInput validate = new ValidateInput();

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputContact = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        middle_name = new javax.swing.JTextField();
        last_name = new javax.swing.JTextField();
        mobile_number = new javax.swing.JTextField();
        email_address = new javax.swing.JTextField();
        submit_button = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(32767, 0));
        clear_all_button = new javax.swing.JButton();
        OutputContact = new javax.swing.JPanel();
        logo1 = new javax.swing.JLabel();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(450, 0), new java.awt.Dimension(0, 0));
        DisplayContact = new javax.swing.JPanel();
        fname_label = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(230, 0), new java.awt.Dimension(0, 0));
        fname_text = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(450, 0), new java.awt.Dimension(0, 0));
        mname_label = new javax.swing.JLabel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(220, 0), new java.awt.Dimension(0, 0));
        mname_text = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(450, 0), new java.awt.Dimension(0, 0));
        lname_label = new javax.swing.JLabel();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(230, 0), new java.awt.Dimension(0, 0));
        lname_text = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(450, 0), new java.awt.Dimension(0, 0));
        mnum_label = new javax.swing.JLabel();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(0, 0));
        mnum_text = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(450, 0), new java.awt.Dimension(0, 0));
        email_label = new javax.swing.JLabel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(200, 5), new java.awt.Dimension(0, 0));
        email_text = new javax.swing.JLabel();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(450, 0), new java.awt.Dimension(0, 0));
        go_back_button = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(12, 0), new java.awt.Dimension(32767, 0));
        save_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contact Book Frog");
        setPreferredSize(new java.awt.Dimension(420, 720));
        setResizable(false);

        InputContact.setBackground(new java.awt.Color(254, 185, 20));
        InputContact.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 15));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        logo.setFocusable(true);
        InputContact.add(logo);

        first_name.setBackground(new java.awt.Color(188, 211, 95));
        first_name.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        first_name.setText("First Name");
        first_name.setForeground(Color.BLACK);
        first_name.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        first_name.setPreferredSize(new java.awt.Dimension(350, 60));
        first_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                first_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                first_nameFocusLost(evt);
            }
        });
        first_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                first_nameKeyTyped(evt);
            }
        });
        InputContact.add(first_name);

        middle_name.setBackground(new java.awt.Color(188, 211, 95));
        middle_name.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        middle_name.setText("Middle Name");
        middle_name.setForeground(Color.BLACK);
        middle_name.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        middle_name.setPreferredSize(new java.awt.Dimension(350, 60));
        middle_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middle_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                middle_nameFocusLost(evt);
            }
        });
        middle_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                middle_nameKeyTyped(evt);
            }
        });
        InputContact.add(middle_name);

        last_name.setBackground(new java.awt.Color(188, 211, 95));
        last_name.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        last_name.setText("Last Name");
        last_name.setForeground(Color.BLACK);
        last_name.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        last_name.setPreferredSize(new java.awt.Dimension(350, 60));
        last_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                last_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                last_nameFocusLost(evt);
            }
        });
        last_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                last_nameKeyTyped(evt);
            }
        });
        InputContact.add(last_name);

        mobile_number.setBackground(new java.awt.Color(188, 211, 95));
        mobile_number.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        mobile_number.setText("Mobile Number");
        mobile_number.setForeground(Color.BLACK);
        mobile_number.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        mobile_number.setPreferredSize(new java.awt.Dimension(350, 60));
        mobile_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mobile_numberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobile_numberFocusLost(evt);
            }
        });
        mobile_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobile_numberKeyTyped(evt);
            }
        });
        InputContact.add(mobile_number);

        email_address.setBackground(new java.awt.Color(188, 211, 95));
        email_address.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        email_address.setText("Email Address");
        email_address.setForeground(Color.BLACK);
        email_address.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        email_address.setPreferredSize(new java.awt.Dimension(350, 60));
        email_address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email_addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_addressFocusLost(evt);
            }
        });
        InputContact.add(email_address);

        submit_button.setBackground(new java.awt.Color(232, 228, 228));
        submit_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        submit_button.setText("Submit");
        submit_button.setFocusPainted(false);
        submit_button.setForeground(Color.BLACK);
        submit_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        submit_button.setContentAreaFilled(false);
        submit_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_button.setOpaque(true);
        submit_button.setPreferredSize(new java.awt.Dimension(90, 40));
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });
        InputContact.add(submit_button);
        InputContact.add(filler2);

        clear_all_button.setBackground(new java.awt.Color(232, 228, 228));
        clear_all_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        clear_all_button.setText("Clear All");
        clear_all_button.setFocusPainted(false);
        clear_all_button.setForeground(Color.BLACK);
        clear_all_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        clear_all_button.setContentAreaFilled(false);
        clear_all_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear_all_button.setOpaque(true);
        clear_all_button.setPreferredSize(new java.awt.Dimension(90, 40));
        clear_all_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_all_buttonActionPerformed(evt);
            }
        });
        InputContact.add(clear_all_button);

        getContentPane().add(InputContact, java.awt.BorderLayout.CENTER);

        OutputContact.setBackground(new java.awt.Color(254, 185, 20));
        OutputContact.setPreferredSize(new java.awt.Dimension(420, 720));
        OutputContact.setVisible(false);

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        logo.setFocusable(true);
        OutputContact.add(logo1);
        OutputContact.add(filler16);

        DisplayContact.setBackground(new java.awt.Color(188, 211, 95));
        DisplayContact.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        DisplayContact.setAutoscrolls(true);
        DisplayContact.setPreferredSize(new java.awt.Dimension(380, 380));
        DisplayContact.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        fname_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        fname_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fname_label.setText("First Name:");
        fname_label.setForeground(Color.BLACK);
        fname_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fname_label.setAlignmentX(-50.0F);
        fname_label.setAlignmentY(0.0F);
        fname_label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        DisplayContact.add(fname_label);
        DisplayContact.add(filler11);

        fname_text.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fname_text.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fname_text.setText("fname");
        fname_text.setForeground(Color.BLACK);
        fname_text.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fname_text.setAlignmentX(-50.0F);
        fname_text.setAlignmentY(0.0F);
        fname_text.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        DisplayContact.add(fname_text);
        DisplayContact.add(filler7);

        mname_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mname_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mname_label.setText("Middle Name:");
        mname_label.setForeground(Color.BLACK);
        mname_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mname_label.setAlignmentX(-50.0F);
        mname_label.setAlignmentY(0.0F);
        mname_label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        DisplayContact.add(mname_label);
        DisplayContact.add(filler12);

        mname_text.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mname_text.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mname_text.setText("mname");
        mname_text.setForeground(Color.BLACK);
        mname_text.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mname_text.setAlignmentX(-50.0F);
        mname_text.setAlignmentY(0.0F);
        mname_text.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        DisplayContact.add(mname_text);
        DisplayContact.add(filler8);

        lname_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lname_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lname_label.setText("Last Name:");
        lname_label.setForeground(Color.BLACK);
        lname_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lname_label.setAlignmentX(-50.0F);
        lname_label.setAlignmentY(0.0F);
        lname_label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        DisplayContact.add(lname_label);
        DisplayContact.add(filler13);

        lname_text.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lname_text.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lname_text.setText("lname");
        lname_text.setForeground(Color.BLACK);
        lname_text.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lname_text.setAlignmentX(-50.0F);
        lname_text.setAlignmentY(0.0F);
        lname_text.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        DisplayContact.add(lname_text);
        DisplayContact.add(filler9);

        mnum_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mnum_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mnum_label.setText("Mobile Number:");
        mnum_label.setForeground(Color.BLACK);
        mnum_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mnum_label.setAlignmentX(-50.0F);
        mnum_label.setAlignmentY(0.0F);
        mnum_label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        DisplayContact.add(mnum_label);
        DisplayContact.add(filler14);

        mnum_text.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mnum_text.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mnum_text.setText("09999999999");
        mnum_text.setForeground(Color.BLACK);
        mnum_text.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mnum_text.setAlignmentX(-50.0F);
        mnum_text.setAlignmentY(0.0F);
        mnum_text.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        DisplayContact.add(mnum_text);
        DisplayContact.add(filler10);

        email_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        email_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email_label.setText("Email Address:");
        email_label.setForeground(Color.BLACK);
        email_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        email_label.setAlignmentX(-50.0F);
        email_label.setAlignmentY(0.0F);
        email_label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        DisplayContact.add(email_label);
        DisplayContact.add(filler15);

        email_text.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        email_text.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email_text.setText("e@mail.com");
        email_text.setForeground(Color.BLACK);
        email_text.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        email_text.setAlignmentX(-50.0F);
        email_text.setAlignmentY(0.0F);
        email_text.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        DisplayContact.add(email_text);

        OutputContact.add(DisplayContact);
        OutputContact.add(filler17);

        go_back_button.setBackground(new java.awt.Color(232, 228, 228));
        go_back_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        go_back_button.setText("Go Back");
        go_back_button.setFocusPainted(false);
        go_back_button.setForeground(Color.BLACK);
        go_back_button.setAlignmentX(10.0F);
        go_back_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        go_back_button.setContentAreaFilled(false);
        go_back_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        go_back_button.setOpaque(true);
        go_back_button.setPreferredSize(new java.awt.Dimension(90, 40));
        OutputContact.add(go_back_button);
        OutputContact.add(filler3);

        save_button.setBackground(new java.awt.Color(232, 228, 228));
        save_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        save_button.setText("Save");
        save_button.setFocusPainted(false);
        save_button.setForeground(Color.BLACK);
        save_button.setAlignmentX(10.0F);
        save_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        save_button.setContentAreaFilled(false);
        save_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_button.setOpaque(true);
        save_button.setPreferredSize(new java.awt.Dimension(90, 40));
        OutputContact.add(save_button);

        getContentPane().add(OutputContact, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
        // Validates the user input before proceeding in showing the output
        if(!validate.checkEmpty(first_name.getText(), middle_name.getText(), last_name.getText(), mobile_number.getText(), email_address.getText())){
            
            if(validate.validateMobileNum(mobile_number.getText().trim())) {
                
                if(validate.validateEmail(email_address.getText().trim())) {
                    // Since everything has been verified
                    // Proceed to the output section
                    InputContact.setVisible(false);                    
                    OutputContact.setVisible(true);

                } else {
                    // If the input email address is not valid
                    showMessageDialog(null, "Not Valid Email Address!");
                }
                
            } else {
                // If the input number is not valid
                showMessageDialog(null, "Not Valid Mobile Number! Ph only!");
            }
            
        } else {
            // If there is an empty field, show warning modal
            showMessageDialog(null, "Please input the missing text field!");
        }
        
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void clear_all_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_all_buttonActionPerformed
        // TODO add your handling code here:
        // Set default
        first_name.setText("First Name");        
        middle_name.setText("Middle Name");
        last_name.setText("Last Name");
        mobile_number.setText("Mobile Number");
        email_address.setText("Email Address");
    }//GEN-LAST:event_clear_all_buttonActionPerformed

    private void first_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_first_nameFocusGained
        // TODO add your handling code here:
        if(first_name.getText().equals("First Name"))
            first_name.setText("");
    }//GEN-LAST:event_first_nameFocusGained

    private void first_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_first_nameFocusLost
        // TODO add your handling code here:
        if(first_name.getText().equals(""))
            first_name.setText("First Name");
    }//GEN-LAST:event_first_nameFocusLost

    private void middle_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middle_nameFocusGained
        // TODO add your handling code here:
        if(middle_name.getText().equals("Middle Name"))
            middle_name.setText("");
    }//GEN-LAST:event_middle_nameFocusGained

    private void middle_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middle_nameFocusLost
        // TODO add your handling code here:
        if(middle_name.getText().equals(""))
            middle_name.setText("Middle Name");
    }//GEN-LAST:event_middle_nameFocusLost

    private void last_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_last_nameFocusGained
        // TODO add your handling code here:
        if(last_name.getText().equals("Last Name"))
            last_name.setText("");
    }//GEN-LAST:event_last_nameFocusGained

    private void last_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_last_nameFocusLost
        // TODO add your handling code here:
        if(last_name.getText().equals(""))
            last_name.setText("Last Name");
    }//GEN-LAST:event_last_nameFocusLost

    private void mobile_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobile_numberFocusGained
        // TODO add your handling code here:
        if(mobile_number.getText().equals("Mobile Number"))
            mobile_number.setText("");
    }//GEN-LAST:event_mobile_numberFocusGained

    private void mobile_numberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobile_numberFocusLost
        // TODO add your handling code here:
        if(mobile_number.getText().equals(""))
            mobile_number.setText("Mobile Number");
    }//GEN-LAST:event_mobile_numberFocusLost

    private void email_addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_addressFocusGained
        // TODO add your handling code here:
        if(email_address.getText().equals("Email Address"))
            email_address.setText("");
    }//GEN-LAST:event_email_addressFocusGained

    private void email_addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_addressFocusLost
        // TODO add your handling code here:
        if(email_address.getText().equals(""))
            email_address.setText("Email Address");
    }//GEN-LAST:event_email_addressFocusLost

    private void mobile_numberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobile_numberKeyTyped
        // TODO add your handling code here:
        validate.onlyNumbers(evt);
    }//GEN-LAST:event_mobile_numberKeyTyped

    private void first_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_first_nameKeyTyped
        // TODO add your handling code here:
        validate.onlyText(evt);
    }//GEN-LAST:event_first_nameKeyTyped

    private void middle_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_middle_nameKeyTyped
        // TODO add your handling code here:
        validate.onlyText(evt);
    }//GEN-LAST:event_middle_nameKeyTyped

    private void last_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_last_nameKeyTyped
        // TODO add your handling code here:
        validate.onlyText(evt);
    }//GEN-LAST:event_last_nameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DisplayContact;
    private javax.swing.JPanel InputContact;
    private javax.swing.JPanel OutputContact;
    private javax.swing.JButton clear_all_button;
    private javax.swing.JTextField email_address;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel email_text;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JTextField first_name;
    private javax.swing.JLabel fname_label;
    private javax.swing.JLabel fname_text;
    private javax.swing.JButton go_back_button;
    private javax.swing.JTextField last_name;
    private javax.swing.JLabel lname_label;
    private javax.swing.JLabel lname_text;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JTextField middle_name;
    private javax.swing.JLabel mname_label;
    private javax.swing.JLabel mname_text;
    private javax.swing.JLabel mnum_label;
    private javax.swing.JLabel mnum_text;
    private javax.swing.JTextField mobile_number;
    private javax.swing.JButton save_button;
    private javax.swing.JButton submit_button;
    // End of variables declaration//GEN-END:variables
}
